### ISSUE TITLE
Segmentation fault on minimal code snippet for L > 1

### ISSUE THREAD

**Issue by wavefunction91** [evaleev/libint#62]
I have recently updated my libint to the latest change set and currently receiving a segmentation fault on the following minimal code snippet for L > 1 (GCC 5.3.1)

```
  libint2::initialize();
  std::vector<libint2::Shell> shells;
  // O STO-3G
  shells.push_back(libint2::Shell{
      {130.7093200,23.8088610,6.4436083},
      {{0,true,{0.15432897,0.53532814,0.44463454}}},
      {{0,0,0}}
      }   
    );  
  shells.push_back(libint2::Shell{
      {5.0331513,1.1695961,0.3803890},
      {{0,true,{-0.09996723,0.39951283,0.70011547}}},
      {{0,0,0}}
      }   
    );  
  shells.push_back(libint2::Shell{
      {5.0331513,1.1695961,0.3803890},
      {{1,true,{0.15591627,0.60768372,0.39195739}}},
      {{0,0,0}}
      }   
    );  


  libint2::Engine engine(libint2::Operator::overlap,3,1,0);
  const auto& buff = engine.results();

  for(auto iShell : shells)
  for(auto jShell : shells){
    std::cout << jShell << std::endl;
    engine.compute(iShell,jShell);
  }

  libint2::finalize();
  return 0;

```

With output
```

Shell:( O={0,0,0}
   {l=0,sph=1}
  130.709 4.25194
  23.8089 4.11229
  6.44361 1.28162

Shell:( O={0,0,0}
   {l=0,sph=1}
  5.03315 -0.239413
  1.1696 0.320234
  0.380389 0.241686

Shell:( O={0,0,0}
   {l=1,sph=1}
  5.03315 1.67545
  1.1696 1.05357
  0.380389 0.166903

Segmentation fault (core dumped)
```

I had originally thought that this was the same as https://github.com/evaleev/libint/issues/48, but I've definitely initialized the libint env at the first line. I'm sure that it's something small that I'm just missing viz the examples in tests/, but I can't seem to find it if it's there.

**Comment by wavefunction91** [comment]
Also, this is how I configured Libint
```
#!/bin/sh
./configure \
--enable-eri=2 \
--with-max-am=5 \
--with-opt-am=3 \
--disable-unrolling \
--enable-generic-code \
--enable-contracted-ints \
--enable-flop-counter \
--with-incdirs='-I/home/dbwy/local/include/eigen3 -I/home/dbwy/local/boost/1.59/include/boost'\
--with-libdirs='-I/home/dbwy/local/boost/1.59/lib'\
--with-cxx=g++ \
--with-cxx-optflags="-std=c++11 -O3" \
--with-cxxgen-optflags="-std=c++11 -O3" \
--prefix=/home/dbwy/local
```

I did enable the FLOP counter if that matters (I usually don't)?

**Comment by evaleev** [comment]
@wavefunction91 it compiles and runs here (only tried clang though). could you please provide a backtrace from the debugger?

**Comment by wavefunction91** [comment]
```
(gdb) where
#0  0x00002aaab94e4ad0 in CR_aB_Z0__0___Overlap_Z1__0___Ab__up_ () from /home/dbwy/devel/chronusq/deps/lib/libint2-beta.so.2
#1  0x00002aaab23ae339 in _overlap_S_P_prereq () from /home/dbwy/devel/chronusq/deps/lib/libint2-beta.so.2
#2  0x00002aaab0f9c077 in _overlap_S_P () from /home/dbwy/devel/chronusq/deps/lib/libint2-beta.so.2
#3  0x000000000040c664 in libint2::Engine::compute1(libint2::Shell const&, libint2::Shell const&) ()
#4  0x000000000048d057 in std::vector<double const*, libint2::detail::ext_stack_allocator<double const*, 78ul> > const& libint2::Engine::compute<libint2::Shell>(libint2::Shell const&, libint2::Shell const&) ()
#5  0x00000000004041aa in main ()
```

**Comment by evaleev** [comment]
@wavefunction91 I will try to re-create the library according to your recipe tomorrow. I have not seen any evidence of issues with this generated code in while. I wonder if you simply have stale object files.

**Comment by wavefunction91** [comment]
I'll attempt to re-create the library tonight and let you know. This is a fresh clone of Libint, so I dont **think** that stale code is the problem, but I'll re-clone to confirm.

**Comment by wavefunction91** [comment]
@evaleev OK, I've regenerated the library with and without the FLOP counter. With the FLOP counter, I get a segmentation fault, without the FLOP counter, the code runs fine.
